### ISSUE TITLE
Bug: NPM package not in sync with Github repository

### ISSUE THREAD

**Issue by Priyadarshanvijay** [OpenApi-5p/5paisa-js#1]
The `5paisajs` package on [https://www.npmjs.com/package/5paisajs](url) doesn't seems to be updated with this repository and is broken as a result. The `const.js` and `utils.js` files are missing from the package repository and as a result the node application is crashing and is unable to start. Hope this issue will be Resolved.

**Comment by ba11b0y** [comment]
@Priyadarshanvijay Thanks for filing this. This has been fixed.
You may now check again by updating using `npm i 5paisajs`
Feel free to open any issues.

**Comment by Priyadarshanvijay** [comment]
> @Priyadarshanvijay Thanks for filing this. This has been fixed.
> You may now check again by updating using `npm i 5paisajs`
> Feel free to open any issues.

Thanks, it's working now!
