### ISSUE TITLE
Feature Request: Getting portfolio data in a JSON format for further operations on it

### ISSUE THREAD

**Issue by Priyadarshanvijay** [OpenApi-5p/5paisa-js#2]
Currently the `getHoldings()` and `getPositions()` functions are fetching the data and printing it out on console, which makes them unusable for further purposes. 
1. Can these methods be changed to get this data back in a JSON format so it can be further processed.
2. Can a token based login system be implemented, which gives back a token via the `login()` function for future use so we don't have to send the Email ID and password for every subsequent request of fetching the user portfolio.

Thanks!

**Comment by ba11b0y** [comment]
> Can these methods be changed to get this data back in a JSON format so it can be further processed.

This should be done definitely! Working on it.

> Can a token based login system be implemented, which gives back a token via the login() function for future use so we don't have to send the Email ID and password for every subsequent request of fetching the user portfolio.

We currently use a cookie based auth system, where in the cookie is valid for 30 minutes.
You can use the same initialised client object for subsequent requests for the given time period.

Let me know if you need more info.

**Comment by ba11b0y** [comment]
@Priyadarshanvijay https://github.com/5paisa/5paisa-js/commit/189834968502b56bec2db838158395891db4d915 Fixes this :tada: 

I have updated the example in the README also.

Let me know if you face any further problems.

Thanks
Rahul.

**Comment by Priyadarshanvijay** [comment]
@invinciblycool thanks a lot!
