### ISSUE TITLE
Result of no records in holdings goes into error block

### ISSUE THREAD

**Issue by GarrySan** [OpenApi-5p/5paisa-js#4]
`try{
    const client = await fetchClient(user);
    const holdings = await client.getHoldings();
    console.log("Holdings are: ")
    console.log(holdings)
  }catch(err){
    console.log(err)
}`

When I ran this code, empty holdings took it to the error block instead of simply returning an empty array

**Comment by ba11b0y** [comment]
This should not happen, in case of no holdings, we return `No holdings found.`
I think this is because of improper promise resolution.
Mind trying something around the lines as in the README?

**Comment by GarrySan** [comment]
Tried with the README code, still going inside the error block and the err message is `No record found.`

**Comment by Manoj-verma** [comment]
Hello sir I want to symbol LTP its possible? Any parameter? We are using automation trading with Tradingview if my condition match when first I get symbol LTP then place order. Symbol LTP is very useful we're calculating stop loss take profit and limit order helping LTP.  Mostly all broker providing LTP from API. But 5paise API doesn't provide LTP if you have holding when I get LTP but I want to without position or holding how to get LTP? If I'm missing something please provide symbol LTP parameter. Sorry for my English   I'm wanting for Your response Thank you for advance
